---
# tasks file for vsftpd_deploy
- name: Install vsftpd, firewalld and Python libs for SElinux
  dnf:
    name: [
      'firewalld',
      'vsftpd',
      'python3-libselinux',
      'python3-libsemanage',
      'python3-policycoreutils'
      ]
    state: latest
- name: Enable and start firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: yes
    daemon_reload: yes
- name: Add rules to firewalld service
  firewalld:
    service: ftp
    permanent: true
    state: enabled
    immediate: yes
  notify:
    firewalld_restart
- name: Copy conf file
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd/vsftpd.conf
    mode: 600
    owner: root
    group: root
  notify:
    vsftpd_restart
- name: Create upload dir
  file:
    path: /var/ftp/pub/upload
    state: directory
    mode: 0777
    setype: public_content_rw_t
- name: Allow anonymous write in SElinux
  seboolean:
    name: ftpd_anon_write
    state: true
    persistent: yes
