FROM node:16-alpine
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./frontend/package*.json ./
USER node
RUN npx browserslist@latest --update-db && npm install
COPY --chown=node:node ./frontend/ .
EXPOSE 3000
# HEALTHCHECK 
CMD ["npm", "start"]