version: '3'

services:

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        tty: true
        container_name: frontend
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
          - database
        networks:
            - frontend
            - backend

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        container_name: backend
        restart: unless-stopped
        ports:
            - 8000:8000
        depends_on:
            - database
        networks:
            - backend

    database:
        image: postgres
        container_name: database
        restart: unless-stopped
        env_file:
            - database.env
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend

networks:
    frontend:
    backend:

volumes:
    pgdata:
